module.exports = {
  CREATE_QUEST: 'CREATE_QUEST',
  CREATED_QUEST: 'CREATED_QUEST',
  COMPLETE_QUEST: 'COMPLETE_QUEST',
  COMPLETED_QUEST: 'COMPLETED_QUEST',
  GOT_QUESTS: 'GOT_QUESTS',
  GOT_CURRENT_HERO: 'GOT_CURRENT_HERO',
  GOT_HEROES: 'GOT_HEROES',
  GOT_MAP: 'GOT_MAP'
};
